<?php

namespace Kregel\Homestead\Tests\Unit\Filters;

use Kregel\Homestead\Filters\LibvirtConnectionFilter;
use Kregel\Homestead\Models\Hypervisor;
use Kregel\Homestead\Tests\AbstractTestCase;

class LibvirtConnectionFilterTest extends AbstractTestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->systemUnderTest = new LibvirtConnectionFilter;
    }

    public function driverAndConnectionTypesDataProvider()
    {
        return [
            // region Xen Hypervisor,
            [
                'xen',
                'xen:///system',
                [
                ]
            ],
            [
                'xen',
                'xen+unix:///system',
                [
                ]
            ],
            [
                'xen',
                'xen://example.com/system',
                [
                ]
            ],
            [
                'xen',
                'xen+tcp://example.com/system',
                [
                ]
            ],
            [
                'xen',
                'xen+ssh://root@example.com/system',
                [
                ]
            ],
            // endregion,
            // region Qemu Hypervisor,
            [
                'qemu',
                'qemu:///session',
                [
                ]
            ],
            [
                'qemu',
                'qemu+unix:///session',
                [
                ]
            ],
            [
                'qemu',
                'qemu:///system',
                [
                ]
            ],
            [
                'qemu',
                'qemu+unix:///system',
                [
                ]
            ],
            [
                'qemu',
                'qemu://example.com/system',
                [
                ]
            ],
            [
                'qemu',
                'qemu+tcp://example.com/system',
                [
                ]
            ],
            [
                'qemu',
                'qemu+ssh://root@example.com/system',
                [
                ]
            ],
            // endregion,
            // region Virtuozzo Hypervisor,
            [
                'vz',
                'vz:///system',
                [
                ]
            ],
            [
                'vz',
                'vz+unix:///system',
                [
                ]
            ],
            [
                'vz',
                'vz://example.com/system',
                [
                ]
            ],
            [
                'vz',
                'vz+tcp://example.com/system',
                [
                ]
            ],
            [
                'vz',
                'vz+ssh://root@example.com/system',
                [
                ]
            ],
            // endregion
            // region VMWare ESX Hypervisor,
            [
                'vpx',
                'vpx:///system',
                [
                ]
            ],
            [
                'vpx',
                'vpx+unix:///system',
                [
                ]
            ],
            [
                'vpx',
                'vpx://example.com/system',
                [
                ]
            ],
            [
                'vpx',
                'vpx+tcp://example.com/system',
                [
                ]
            ],
            [
                'vpx',
                'vpx+ssh://root@example.com/system',
                [
                ]
            ],
            [
                'esx',
                'esx:///system',
                [
                ]
            ],
            [
                'esx',
                'esx+unix:///system',
                [
                ]
            ],
            [
                'esx',
                'esx://example.com/system',
                [
                ]
            ],
            [
                'esx',
                'esx+tcp://example.com/system',
                [
                ]
            ],
            [
                'esx',
                'esx+ssh://root@example.com/system',
                [
                ]
            ],
            [
                'gsx',
                'gsx:///system',
                [
                ]
            ],
            [
                'gsx',
                'gsx+unix:///system',
                [
                ]
            ],
            [
                'gsx',
                'gsx://example.com/system',
                [
                ]
            ],
            [
                'gsx',
                'gsx+tcp://example.com/system',
                [
                ]
            ],
            [
                'gsx',
                'gsx+ssh://root@example.com/system',
                [
                ]
            ],
            // endregion
            // region Qemu Hypervisor,
            [
                'bhyve',
                'bhyve:///session',
                [
                ]
            ],
            [
                'bhyve',
                'bhyve+unix:///session',
                [
                ]
            ],
            [
                'bhyve',
                'bhyve+ssh://root@example.com/system',
                [
                ]
            ],
            // endregion,

        ];
    }

    /**
     * @dataProvider driverAndConnectionTypesDataProvider
     */
    public function testHandleSuccess(string $driver, string $desiredConnectionString, array $hypervisorModel)
    {
        $hypervisor = new Hypervisor([
            'hypervisor' => $driver
        ]);

        $this->assertSame($desiredConnectionString, $this->systemUnderTest->filter($hypervisor));
    }
}
